### ISSUE TITLE
WebRTC is not supported by this browser

### ISSUE THREAD

**Issue by dukizwe** [matallui/artico#13]
This is the error i got while try to use it in react native

**Comment by matallui** [comment]
You need to enable some poly fills in your app for it to work properly, if I remember correctly. I'll create some docs soon with better instructions.

**Comment by matallui** [comment]
@dukizwe Take a look at the polyfills logic. You'll need this to get Artico working on an Expo app.

https://github.com/matallui/artico/blob/main/apps/demo-expo/components/polyfills.ts

On a different note, please consider giving the repo a start, so we can get more visibility and grow the project. Thank you so much for giving it a try!! 🚀
