### ISSUE TITLE
WebRTC: ICE failed, add a TURN server and see about:webrtc for more details

### ISSUE THREAD

**Issue by dukizwe** [matallui/artico#14]
No matter what I do, I keep encountering the error message `WebRTC: ICE failed, add a TURN server and see about
for more details` even after adding a TURN server:

Here is how I have configured the TURN server:

```js
const options: Partial<ArticoOptions> = { 
          debug: 4,
          rtcConfig: { 
                    iceServers: [{ urls: 'stun:[stun.l.google.com:19302]' }] 
          } 
};
```

I have also reviewed the <a href="https://github.com/matallui/artico/blob/main/apps/demo/src/app/call/demo.tsx">example project</a>, but I couldn't find any specific TURN server configuration there, yet it still works. How did you manage to get it working?

**Comment by matallui** [comment]
Hey @dukizwe! Can you provide a reproduction example?
Do you have a github repo with the app you're testing with or something?

**Comment by dukizwe** [comment]
@matallui  here's the working demo:

https://github.com/dukizwe/artico-demo/blob/main/src/app/call/demo.tsx

**Comment by dukizwe** [comment]
@matallui any feedback ??

**Comment by matallui** [comment]
@dukizwe Do your network conditions allow for [NAT traversal](https://tailscale.com/blog/how-nat-traversal-works)? Not all networks will allow this (e.g., corporate networks usually don't), meaning a peer located outside a corporate network wouldn't be able to call someone inside that network (not without a TURN server, which you don't have configured).

**Comment by matallui** [comment]
I deployed your app and was able to call from my phone (Verizon network) to my laptop on the home Wi-Fi. So... I can only assume that your network conditions don't allow NAT traversal and, therefore, you'd have to use  a TURN server.

**Comment by matallui** [comment]
Haven't heard any updates on this, so closing the issue with the assumption this is purely based on your network conditions.
