### ISSUE TITLE
Install failure in Linux:  npm install @rtco/client 

### ISSUE THREAD

**Issue by warrenchopin** [matallui/artico#15]
Hello,

I tried to install in my Linux device (Debian, installed by [Termux_XFCE](https://github.com/phoenixbyrd/Termux_XFCE) ). I got following errors:
```
> npm install @rtco/client
npm ERR! code 1
npm ERR! path /home/w/node_modules/utf-8-validate
npm ERR! command failed
npm ERR! command sh -c node-gyp-build
npm ERR! gyp info it worked if it ends with ok
npm ERR! gyp info using node-gyp@10.0.1
npm ERR! gyp info using node@21.6.2 | android | arm64
npm ERR! gyp info find Python using Python version 3.11.2 found at "/usr/bin/python3"
npm ERR! gyp info spawn /usr/bin/python3
npm ERR! gyp info spawn args [
npm ERR! gyp info spawn args '/data/data/com.termux/files/usr/lib/node_modules/npm/node_modules/node-gyp/gyp/gyp_main.py',
npm ERR! gyp info spawn args 'binding.gyp',
npm ERR! gyp info spawn args '-f',
npm ERR! gyp info spawn args 'make',
npm ERR! gyp info spawn args '-I',
npm ERR! gyp info spawn args 
...[a lot of error messages]...
```

Is Artico still installable in general? I want to know whether it is a problem specific to my device, or not.

I really appreciate your help. Thanks in advance.

**Comment by matallui** [comment]
@warrenchopin I would assume it should be installable on Linux, I don't see why not. I don't currently have a Linux machine to test on, but some quick googling makes me believe the issue is not related to Artico packages.

Check out: https://github.com/nodejs/node-gyp/issues/2273
