### ISSUE TITLE
npm install @rtco/client failed

### ISSUE THREAD

**Issue by stephenprogramscoffee** [matallui/artico#20]
Getting an error installing `@rtco/client` in my Next.js app.

```
npm ERR! code EUNSUPPORTEDPROTOCOL
npm ERR! Unsupported URL Type "workspace:": workspace:*

npm ERR! A complete log of this run can be found in: /home/stephensuniega/.npm/_logs/2024-08-26T06_37_52_335Z-debug-0.log
```

**Current OS**:
- Linux

**Steps to reproduce**:
- `npm install @rtco/client`

**Edited**:
- Tried to run `npm install @rtco/client` in my Expo App, still getting the same error. I think the error is related to the new release version.

**Comment by matallui** [comment]
@stephenprogramscoffee Can you try the latest v0.2.16? Should be fixed now.
