### ISSUE TITLE
Support the reuse of peer connections.

### ISSUE THREAD

**Issue by molvqingtai** [matallui/artico#24]
Hello, thank you for creating Artico. I am using it in my extension([WebChat](https://github.com/molvqingtai/WebChat)).

Is it possible to reuse an established peer connection? For example, when a user opens multiple browser tabs, like this:

```javascript
// tabA
const peerA = 'xxx';
new Artico({ id: peerA });

// tabB
const peerB = 'xxx';
new Artico({ id: peerB });
```

Since both peerA and peerB belong to the same user, is there a way to associate their connections (support passing connection information)? If a connection already exists, it should reuse the connection instead of creating a new one.

I tried using the same ID for both peerA and peerB, but this caused peerB to be unable to connect.

**Comment by matallui** [comment]
Hey @molvqingtai! Thanks for using Artico.

Regarding your question, that's really not possible for multiple reasons.

And even if it was possible, it'd be a major security concern IMO.

**Comment by molvqingtai** [comment]
> Hey @molvqingtai! Thanks for using Artico.
> 
> Regarding your question, that's really not possible for multiple reasons.
> 
> And even if it was possible, it'd be a major security concern IMO.

Thank you. I really didn’t consider the security issue and should give up this approach.
