### ISSUE TITLE
Unable to answer call in Edge

### ISSUE THREAD

**Issue by AnupamKris** [matallui/artico#7]
This is a simple implementation of the `@rtco.client` library.
[**GitHub** ](https://github.com/AnupamKris/simplechat)| [**VercelHosted**](https://simplechat-pearl.vercel.app)

So, when I attempt to call from **Edge** and answer it from any other browser (tried: OperaGX, Chrome Mobile), the answer call function is working correctly and the call is opening, but when I call from any browser (tried: Edge, OperaGX, Chrome Mobile) to **Edge**, the answer call function won't work, i.e. the `call.on("open")` is not being triggered.

**Comment by matallui** [comment]
I just installed Microsoft Edge on macOS and it works fine there.
I don't have a Windows machine to test this on, but once I find one I can give it a try.

**Comment by AnupamKris** [comment]
It's fixed in `v0.2.3`. Everything works as expected now.
